[project]
name = "mini-coding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docker>=7.2.0",
    "langfuse>=4.14.5",
    "openai>=3.1.0",
    "pyarrow>=18.0.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]
